from pathlib import Path
p=Path('/mnt/data/qlp_work/src/routes/_authenticated/pedidos.novo.tsx')
s=p.read_text()
s=s.replace('import { saveCliente } from "@/lib/app-data.functions";\n','')
s=s.replace('import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";\n','import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";\n')
s=s.replace('  const salvarCliente = useServerFn(saveCliente);\n','')
s=s.replace('  const [clienteId, setClienteId] = useState<string>("novo");','  const [clienteId, setClienteId] = useState<string>("");')
old='''  useEffect(() => {\n    if (clienteId !== "novo") {\n      const c = clientes.find((x) => x.id === clienteId);\n      if (c) {\n        setNome(c.nome);\n        setTelefone(c.telefone ?? "");\n        setEndereco(c.endereco ?? "");\n      }\n    }\n  }, [clienteId, clientes]);'''
new='''  useEffect(() => {\n    const c = clientes.find((x) => x.id === clienteId);\n    if (c) {\n      setNome(c.nome);\n      setTelefone(c.telefone ?? "");\n      setEndereco(c.endereco ?? "");\n    } else {\n      setNome("");\n      setTelefone("");\n      setEndereco("");\n    }\n  }, [clienteId, clientes]);'''
s=s.replace(old,new)
old='''    if (!produto) return toast.error("Escolha um produto");\n    if (!nome.trim()) return toast.error("Informe o nome do cliente");\n    if (!quantidadeValida) return toast.error("Informe uma quantidade válida");\n    setSaving(true);\n\n    let finalClienteId = clienteId === "novo" ? null : clienteId;\n    if (clienteId === "novo" && nome.trim()) {\n      try {\n        const novo = await salvarCliente({ data: { nome: nome.trim(), telefone, endereco, observacoes: "" } });\n        finalClienteId = novo?.id ?? null;\n      } catch (error) {\n        setSaving(false);\n        return toast.error("Erro ao cadastrar cliente", { description: error instanceof Error ? error.message : "Tente novamente" });\n      }\n    }'''
new='''    if (!clienteId) {\n      return toast.error("Selecione um cliente cadastrado", {\n        description: "Cadastre o cliente na tela Clientes antes de lançar o pedido.",\n      });\n    }\n    if (!produto) return toast.error("Escolha um produto");\n    if (!nome.trim()) return toast.error("Cliente selecionado inválido");\n    if (!quantidadeValida) return toast.error("Informe uma quantidade válida");\n    if (tipo === "entrega" && !endereco.trim()) return toast.error("Informe o endereço da entrega");\n    setSaving(true);\n\n    const finalClienteId = clienteId;'''
s=s.replace(old,new)
s=s.replace('''      endereco: tipo === "entrega" ? endereco : null,''','''      endereco: tipo === "entrega" ? endereco.trim() : null,''')
old='''            <div className="space-y-2">\n              <Label>Cliente cadastrado</Label>\n              <Select value={clienteId} onValueChange={setClienteId}>\n                <SelectTrigger><SelectValue /></SelectTrigger>\n                <SelectContent>\n                  <SelectItem value="novo">+ Novo cliente</SelectItem>\n                  {clientes.map((c) => <SelectItem key={c.id} value={c.id}>{c.nome}</SelectItem>)}\n                </SelectContent>\n              </Select>\n            </div>'''
new='''            <div className="space-y-2">\n              <Label>Cliente cadastrado *</Label>\n              <div className="flex flex-col sm:flex-row gap-2">\n                <Select value={clienteId || undefined} onValueChange={setClienteId}>\n                  <SelectTrigger className="flex-1"><SelectValue placeholder="Selecione um cliente..." /></SelectTrigger>\n                  <SelectContent>\n                    {clientes.length === 0 ? (\n                      <SelectItem value="__none__" disabled>Nenhum cliente cadastrado</SelectItem>\n                    ) : clientes.map((c) => (\n                      <SelectItem key={c.id} value={c.id}>{c.nome}{c.telefone ? ` — ${c.telefone}` : ""}</SelectItem>\n                    ))}\n                  </SelectContent>\n                </Select>\n                <Button type="button" variant="outline" onClick={() => navigate({ to: "/clientes" })}>\n                  Cadastrar cliente\n                </Button>\n              </div>\n              <p className="text-xs text-muted-foreground">\n                O pedido agora usa apenas clientes já cadastrados. Cadastre ou edite clientes na tela Clientes.\n              </p>\n            </div>'''
s=s.replace(old,new)
s=s.replace('''                <Input value={nome} onChange={(e) => setNome(e.target.value)} required />''','''                <Input value={nome} readOnly placeholder="Selecione um cliente acima" className="bg-muted/40" required />''')
s=s.replace('''                <Input value={telefone} onChange={(e) => setTelefone(e.target.value)} placeholder="(11) 99999-9999" />''','''                <Input value={telefone} readOnly placeholder="Telefone vindo do cadastro" className="bg-muted/40" />''')
s=s.replace('''                <Textarea value={endereco} onChange={(e) => setEndereco(e.target.value)} />''','''                <Textarea value={endereco} onChange={(e) => setEndereco(e.target.value)} placeholder="Endereço do cadastro do cliente. Ajuste aqui se esta entrega for em outro local." />''')
# remove unused import useServerFn if no longer used
s=s.replace('import { useServerFn } from "@tanstack/react-start";\n','')
p.write_text(s)
